In [1]:
import numpy as np
import pandas as pd
from functools import reduce
import os
import statsmodels.api as sm

In [3]:
df=pd.read_pickle('../data/Portfolio Beta and Return Daily/beta.pickle')

In [7]:
df.dropna()

,1,2,3,4,5,6,7,8,9,10
2007-12-31,0.491387,0.683544,0.784919,0.857999,0.917366,0.975309,1.03179,1.10185,1.20136,1.42221
2008-01-02,0.472752,0.662835,0.76885,0.846641,0.909021,0.968601,1.02729,1.09895,1.19896,1.41884
2008-01-03,0.4631,0.655192,0.762727,0.841363,0.904773,0.965668,1.02531,1.09694,1.19725,1.41686
2008-01-04,0.458933,0.6493,0.758117,0.83819,0.90261,0.964672,1.02479,1.09655,1.1972,1.41476
2008-01-07,0.451718,0.642765,0.753624,0.833924,0.899396,0.962379,1.02284,1.09462,1.19353,1.41216
...,...,...,...,...,...,...,...,...,...,...
2011-08-18,0.474636,0.636009,0.758403,0.84476,0.921998,0.996352,1.07592,1.16785,1.27749,1.54491
2011-08-19,0.468626,0.630361,0.750912,0.837668,0.913729,0.987998,1.06587,1.15688,1.26511,1.52688
2011-08-22,0.470151,0.631639,0.751564,0.837108,0.913262,0.987544,1.06542,1.15577,1.26451,1.52238
2011-08-23,0.469227,0.63405,0.753559,0.838269,0.914697,0.98892,1.06684,1.15752,1.26667,1.52831
2011-08-24,0.471077,0.632218,0.751479,0.835807,0.911384,0.985202,1.06269,1.15187,1.25989,1.51495

In [8]:
df.mean()

1     0.456803
2     0.622310
3     0.727481
4     0.813204
5     0.890975
6     0.966032
7     1.046653
8     1.138509
9     1.262916
10    1.544473
dtype: float64